Convert from `command` discovery to hard-coded paths

diff --git a/pacctl b/pacctl
--- a/pacctl
+++ b/pacctl
@@ -8,20 +8,20 @@
 NEWLINE='
 '
 
-CURL_BIN=$(command -v curl)
-GREP_BIN=$(command -v grep)
-PACMANBIN=$(command -v pacman)
-REFLECTOR=$(command -v reflector)
-SED_BIN=$(command -v sed)
-SUDO_BIN=$(command -v sudo)
-
-[ -z "${CURL_BIN}" ] && echo "Could not find curl" && exit 2
-[ -z "${GREP_BIN}" ] && echo "Could not find grep" && exit 3
-[ -z "${PACMANBIN}" ] && echo "Could not find pacman" && exit 5
-[ -z "${SED_BIN}" ] && echo "Could not find sed" && exit 7
+[ -e /usr/bin/comm ] || echo "Could not find comm" && exit 2
+[ -e /usr/bin/curl ] || echo "Could not find curl" && exit 2
+[ -e /bin/grep ] || echo "Could not find grep" && exit 3
+[ -e /usr/bin/pacman ] || echo "Could not find pacman" && exit 5
+[ -e /usr/bin/pactree ] || echo "Could not find pactree" && exit 5
+[ -e /usr/bin/printf ] || echo "Could not find printf" && exit 5
+[ -e /usr/bin/reflector ] || echo "Could not find reflector" && exit 5
+[ -e /bin/sed ] || echo "Could not find sed" && exit 7
+[ -e /usr/bin/sort ] || echo "Could not find sort" && exit 5
+[ -e /usr/bin/sudo ] || echo "Could not find sudo" && exit 5
+[ -e /usr/bin/tr ] || echo "Could not find tr" && exit 5
 
 GET_PRIVILEGE() {
-  while ! ${SUDO_BIN} true; do
+  while ! /usr/bin/sudo true; do
     continue
   done
 }
@@ -29,7 +29,7 @@ GET_PRIVILEGE() {
 case "${1}" in
   dl|down|download)
     case "${2}" in
-      updates) GET_PRIVILEGE && ${SUDO_BIN} pacman -Syuw --noconfirm;;
+      updates) GET_PRIVILEGE && /usr/bin/sudo /usr/bin/pacman -Syuw --noconfirm;;
     esac
     ;;
   ls|list)
@@ -37,9 +37,9 @@ case "${1}" in
       CATEGORY="${1}"
       shift
       for PACKAGE in ${@}; do
-        printf '\033[2K\rThinking about %s:%s' "${CATEGORY}" "${PACKAGE}" > /dev/stderr
-        pactree -ul "${PACKAGE}" > /dev/null 2>&1 && OPTS=ul || OPTS=sul
-        NEW_PACKAGES="$(pactree "-${OPTS}" "${PACKAGE}")"
+        /usr/bin/printf '\033[2K\rThinking about %s:%s' "${CATEGORY}" "${PACKAGE}" > /dev/stderr
+        /usr/bin/pactree -ul "${PACKAGE}" > /dev/null 2>&1 && OPTS=ul || OPTS=sul
+        NEW_PACKAGES="$(/usr/bin/pactree "-${OPTS}" "${PACKAGE}")"
         if [ -n "${NEW_PACKAGES}" ]; then
           if [ -n "${PACKAGE_LIST}" ]; then
             PACKAGE_LIST="${PACKAGE_LIST}${NEWLINE}"
@@ -47,65 +47,65 @@ case "${1}" in
           PACKAGE_LIST="${PACKAGE_LIST}${NEW_PACKAGES}"
         fi
       done
-      printf "\033[2K\r" > /dev/stderr
-      printf '%s\n' "$(echo "${PACKAGE_LIST}" | sort -u | tr '\n' ' ')"
+      /usr/bin/printf "\033[2K\r" > /dev/stderr
+      /usr/bin/printf '%s\n' "$(echo "${PACKAGE_LIST}" | /usr/bin/sort -u | /usr/bin/tr '\n' ' ')"
     }
 
     case "${2}" in
-      base) pactree -ul base | sort | tr '\n' ' ';;
-      base-devel) THINK_ABOUT base-devel $(pacman -Sgq base-devel | sort | tr '\n' ' ');;
+      base) /usr/bin/pactree -ul base | /usr/bin/sort | /usr/bin/tr '\n' ' ';;
+      base-devel) THINK_ABOUT base-devel $(/usr/bin/pacman -Sgq base-devel | /usr/bin/sort | /usr/bin/tr '\n' ' ');;
       base-extra) THINK_ABOUT base-extra linux linux-headers linux-hardened linux-hardened-headers linux-lts linux-lts-headers linux-zen-headers linux-firmware grub refind syslinux nano vim sudo;;
-      core) THINK_ABOUT core $(pacman -Slq core | sort | tr '\n' ' ');;
-      expanded-base) printf '%s\n%s\n%s\n' "$(pacctl list base | tr ' ' '\n')"p "$(pacctl list base-devel | tr ' ' '\n')" "$(pacctl list base-extra | tr ' ' '\n')" | sort -u | tr '\n' ' '; echo;;
-      explicit) pacman -Qenq | sort | tr '\n' ' ';;
-      modded-configs) pacman -Qii | grep '^MODIFIED' | sed 's/MODIFIED\t//g' ;;
-      repo) pacman -Slq "${3}" | sort | tr '\n' ' ';;
-      xorg) THINK_ABOUT xorg $(pacman -Sgq xorg | sort | tr '\n' ' ');;
+      core) THINK_ABOUT core $(/usr/bin/pacman -Slq core | /usr/bin/sort | /usr/bin/tr '\n' ' ');;
+      expanded-base) /usr/bin/printf '%s\n%s\n%s\n' "$("${0}" list base | /usr/bin/tr ' ' '\n')"p "$("${0}" list base-devel | /usr/bin/tr ' ' '\n')" "$("${0}" list base-extra | /usr/bin/tr ' ' '\n')" | /usr/bin/sort -u | /usr/bin/tr '\n' ' '; echo;;
+      explicit) /usr/bin/pacman -Qenq | /usr/bin/sort | /usr/bin/tr '\n' ' ';;
+      modded-configs) /usr/bin/pacman -Qii | /bin/grep '^MODIFIED' | /bin/sed 's/MODIFIED\t//g' ;;
+      repo) /usr/bin/pacman -Slq "${3}" | /usr/bin/sort | /usr/bin/tr '\n' ' ';;
+      xorg) THINK_ABOUT xorg $(/usr/bin/pacman -Sgq xorg | /usr/bin/sort | /usr/bin/tr '\n' ' ');;
     esac
   ;;
   rm|rem|remove)
     INSTALLED="$(mktemp)"
-    pacman -Qq | sort > "${INSTALLED}"
+    /usr/bin/pacman -Qq | /usr/bin/sort > "${INSTALLED}"
     COMPARETO="$(mktemp)"
     GET_PRIVILEGE || exit 1
     case "${2}" in
-      all-but-base) pacctl list expanded-base | tr ' ' '\n' | sort > "${COMPARETO}"; ${SUDO_BIN} pacman -R $(comm -23 "${INSTALLED}" "${COMPARETO}");;
-      all-but-core) pacctl list core | tr ' ' '\n' | sort > "${COMPARETO}"; ${SUDO_BIN} pacman -R $(comm -23 "${INSTALLED}" "${COMPARETO}");;
-      all-but-xorg) echo "$(pacctl list xorg | tr ' ' '\n')${NEWLINE}$(pacctl list core | tr ' ' '\n')" | sort -u > "${COMPARETO}"; ${SUDO_BIN} pacman -R $(comm -23 "${INSTALLED}" "${COMPARETO}");;
+      all-but-base) "${0}" list expanded-base | /usr/bin/tr ' ' '\n' | /usr/bin/sort > "${COMPARETO}"; /usr/bin/sudo /usr/bin/pacman -R $(/usr/bin/comm -23 "${INSTALLED}" "${COMPARETO}");;
+      all-but-core) "${0}" list core | /usr/bin/tr ' ' '\n' | /usr/bin/sort > "${COMPARETO}"; /usr/bin/sudo /usr/bin/pacman -R $(/usr/bin/comm -23 "${INSTALLED}" "${COMPARETO}");;
+      all-but-xorg) echo "$("${0}" list xorg | /usr/bin/tr ' ' '\n')${NEWLINE}$("${0}" list core | /usr/bin/tr ' ' '\n')" | /usr/bin/sort -u > "${COMPARETO}"; /usr/bin/sudo /usr/bin/pacman -R $(/usr/bin/comm -23 "${INSTALLED}" "${COMPARETO}");;
       orphans)
-        PKG_LIST="$(pacman -Qtqd 2> /dev/null)"
+        PKG_LIST="$(/usr/bin/pacman -Qtqd 2> /dev/null)"
         [ -z "${PKG_LIST}" ] && echo "No orphaned packages found." && exit 0
-        ${SUDO_BIN} pacman -Rnsc ${PKG_LIST}
+        /usr/bin/sudo /usr/bin/pacman -Rnsc ${PKG_LIST}
         ;;
     esac
   ;;
   up|upd|updt|update)
     case "${2}" in
-      ignored) pacman -S --needed --noconfirm "$(grep '^IgnorePkg' /etc/pacman.conf | sed 's/.*= //g')";;
+      ignored) /usr/bin/pacman -S --needed --noconfirm "$(/bin/grep '^IgnorePkg' /etc/pacman.conf | /bin/sed 's/.*= //g')";;
       zfs)
         GET_PRIVILEGE || exit 1
-        ${SUDO_BIN} pacman -Sy || exit 2
+        /usr/bin/sudo /usr/bin/pacman -Sy || exit 2
         VERSION_LESSTHAN() {
           [ "${1}" != "${2}" ] && true || false
         }
-        printf "\033[1;34m::\033[97m ZFS Kernel Information:\033[0m\n"
-        INSTALLED_KERNEL="$(pacman -Qqs Linux kernel | grep '^linux' | grep -v headers)"
-        INSTALLED_HEADER="$(pacman -Qqs Linux kernel | grep headers | grep -v api)"
-        LOCAL_KERNEL_VER="$(pacman -Qi "${INSTALLED_KERNEL}" | grep 'Version' | sed 's/.*: //g')"
+        /usr/bin/printf "\033[1;34m::\033[97m ZFS Kernel Information:\033[0m\n"
+        INSTALLED_KERNEL="$(/usr/bin/pacman -Qqs Linux kernel | /bin/grep '^linux' | /bin/grep -v headers)"
+        INSTALLED_HEADER="$(/usr/bin/pacman -Qqs Linux kernel | /bin/grep headers | /bin/grep -v api)"
+        LOCAL_KERNEL_VER="$(/usr/bin/pacman -Qi "${INSTALLED_KERNEL}" | /bin/grep 'Version' | /bin/sed 's/.*: //g')"
         case "${INSTALLED_KERNEL}" in
           linux-zen) OFFICIAL_REPO="extra";;
                   *) OFFICIAL_REPO="core";;
         esac
-        REPO_KERNEL_VER="$(pacman -Si "${OFFICIAL_REPO}/${INSTALLED_KERNEL}" | grep 'Version' | sed 's/.*: //g')"
-        ZFS_KERNEL_VER="$(pacman -Si "zfs-${INSTALLED_KERNEL}/${INSTALLED_KERNEL}" | grep 'Version' | sed 's/.*: //g')"
-        ZFS_MODULE_VER="$(pacman -Si "archzfs/zfs-${INSTALLED_KERNEL}" | grep 'Version' | sed 's/.*: //g')"
-        ZFS_MOD_CORVER="$(pacman -Si "zfs-${INSTALLED_KERNEL}" | grep 'Depends' | tr ' ' '\n' | grep "${INSTALLED_KERNEL}" | cut -d= -f2)"
-        ZFS_UTILS_VRSN="$(pacman -Si "zfs-utils" | grep 'Version' | sed 's/ //g' | cut -d: -f2)"
-        printf '%-30s%-30s\n'   " local/${INSTALLED_KERNEL}"                   "${LOCAL_KERNEL_VER}"
-        printf '%-30s%-30s\n'   " ${OFFICIAL_REPO}/${INSTALLED_KERNEL}"        "${REPO_KERNEL_VER}"
-        printf '%-30s%-30s\n'   " zfs-${INSTALLED_KERNEL}/${INSTALLED_KERNEL}" "${ZFS_KERNEL_VER}"
-        printf '%-30s%-30s\n'   " archzfs/zfs-${INSTALLED_KERNEL}"             "$(echo "${ZFS_MODULE_VER}" | sed 's/.*_//g')"
-        printf '%-30s%-30s\n\n' " zfs-${INSTALLED_KERNEL}/zfs-utils"           "${ZFS_UTILS_VRSN%%-*}"
+        REPO_KERNEL_VER="$(/usr/bin/pacman -Si "${OFFICIAL_REPO}/${INSTALLED_KERNEL}" | /bin/grep 'Version' | /bin/sed 's/.*: //g')"
+        ZFS_KERNEL_VER="$(/usr/bin/pacman -Si "zfs-${INSTALLED_KERNEL}/${INSTALLED_KERNEL}" | /bin/grep 'Version' | /bin/sed 's/.*: //g')"
+        ZFS_MODULE_VER="$(/usr/bin/pacman -Si "archzfs/zfs-${INSTALLED_KERNEL}" | /bin/grep 'Version' | /bin/sed 's/.*: //g')"
+        ZFS_MOD_CORVER="$(/usr/bin/pacman -Si "zfs-${INSTALLED_KERNEL}" | /bin/grep 'Depends' | /usr/bin/tr ' ' '\n' | /bin/grep "${INSTALLED_KERNEL}" | cut -d= -f2)"
+        ZFS_UTILS_VRSN="$(/usr/bin/pacman -Si "zfs-utils" | /bin/grep 'Version' | /bin/sed 's/ //g' | cut -d: -f2)"
+        /usr/bin/printf '%-30s%-30s\n'   " local/${INSTALLED_KERNEL}"                   "${LOCAL_KERNEL_VER}"
+        /usr/bin/printf '%-30s%-30s\n'   " ${OFFICIAL_REPO}/${INSTALLED_KERNEL}"        "${REPO_KERNEL_VER}"
+        /usr/bin/printf '%-30s%-30s\n'   " zfs-${INSTALLED_KERNEL}/${INSTALLED_KERNEL}" "${ZFS_KERNEL_VER}"
+        /usr/bin/printf '%-30s%-30s\n'   " archzfs/zfs-${INSTALLED_KERNEL}"             "$(echo "${ZFS_MODULE_VER}" | /bin/sed 's/.*_//g')"
+        /usr/bin/printf '%-30s%-30s\n\n' " zfs-${INSTALLED_KERNEL}/zfs-utils"           "${ZFS_UTILS_VRSN%%-*}"
         if [ "${REPO_KERNEL_VER%.zen*}" = "${ZFS_MOD_CORVER%.zen*}" ]; then
           ARCHZFS_STATUS="current with"
           UPGRADED_KERNEL="${INSTALLED_KERNEL}"
@@ -117,48 +117,42 @@ case "${1}" in
           [ -n "${INSTALLED_HEADER}" ] && UPGRADED_HEADER="${INSTALLED_HEADER}=${ZFS_MOD_CORVER}"
           UPGRADED_MODULE="zfs-${INSTALLED_KERNEL}=${ZFS_MODULE_VER}"
         fi
-        printf '\033[1;33m ->\033[0m Repo archzfs is %s official.\n' "${ARCHZFS_STATUS}"
+        /usr/bin/printf '\033[1;33m ->\033[0m Repo archzfs is %s official.\n' "${ARCHZFS_STATUS}"
         if VERSION_LESSTHAN "${LOCAL_KERNEL_VER%.zen*}" "${ZFS_MOD_CORVER%.zen*}"; then
-          printf '\033[1;33m ->\033[0m ZFS module upgrade from %s to %s available.\n' "${LOCAL_KERNEL_VER}" "${ZFS_MOD_CORVER}"
+          /usr/bin/printf '\033[1;33m ->\033[0m ZFS module upgrade from %s to %s available.\n' "${LOCAL_KERNEL_VER}" "${ZFS_MOD_CORVER}"
           if [ "${ZFS_KERNEL_VER%.zen*}" = "${ZFS_MOD_CORVER%.zen*}" ] || [ "${REPO_KERNEL_VER%.zen*}" = "${ZFS_MOD_CORVER%.zen*}" ]; then
-            ${SUDO_BIN} pacman -S --needed --noconfirm ${UPGRADED_KERNEL} ${UPGRADED_HEADER} ${UPGRADED_MODULE} zfs-utils
+            /usr/bin/sudo /usr/bin/pacman -S --needed --noconfirm ${UPGRADED_KERNEL} ${UPGRADED_HEADER} ${UPGRADED_MODULE} zfs-utils
           else
-            printf '\033[1;33m ->\033[0m Cannot find %s.\n' "${UPGRADED_KERNEL}"
+            /usr/bin/printf '\033[1;33m ->\033[0m Cannot find %s.\n' "${UPGRADED_KERNEL}"
           fi
         else
-          printf '\033[1;33m ->\033[0m No update available.\n'
+          /usr/bin/printf '\033[1;33m ->\033[0m No update available.\n'
         fi
       ;;
       mirror*)
-        [ -z "${REFLECTOR}" ] && echo "Could not find reflector" && exit 6
         GEOIPURL="http://api.geoiplookup.net/"
 
-        if [ -n "${SUDO_BIN}" ]; then
-          COMMAND="${SUDO_BIN} ${REFLECTOR}"
-          GET_PRIVILEGE || exit 1
-        else
-          COMMAND="${REFLECTOR}"
-        fi
+        GET_PRIVILEGE || exit 1
 
         if [ -n "${3}" ]; then
-          printf "\033[1;34m::\033[97m User-determined county...\033[0m\n"
+          /usr/bin/printf "\033[1;34m::\033[97m User-determined county...\033[0m\n"
           COUNTRY="${3}"
         else
-          printf "\033[1;34m::\033[97m Geolocating county...\033[0m\n"
-          COUNTRY="$(${CURL_BIN} -s ${GEOIPURL} | grep countryname | sed 's/.*<countryname>\(.*\)<\/countryname>.*/\1/g')"
+          /usr/bin/printf "\033[1;34m::\033[97m Geolocating county...\033[0m\n"
+          COUNTRY="$(/usr/bin/curl -s ${GEOIPURL} | /bin/grep countryname | /bin/sed 's/.*<countryname>\(.*\)<\/countryname>.*/\1/g')"
         fi
 
-        printf " %s\n" "${COUNTRY}"
-        printf "\033[1;34m::\033[97m Determining Best Mirrors...\033[0m\n"
-        ${COMMAND} -p https -l 10 -f 5 -c "${COUNTRY}" -x mirror.theash.xyz -x ftp.sudhip.com -x dfw.mirror.rackspace.com --sort rate --save /etc/pacman.d/mirrorlist
-        ${GREP_BIN} '^Server' /etc/pacman.d/mirrorlist | ${SED_BIN} 's/\(.*\)/ \1/g'
+        /usr/bin/printf " %s\n" "${COUNTRY}"
+        /usr/bin/printf "\033[1;34m::\033[97m Determining Best Mirrors...\033[0m\n"
+        /usr/bin/sudo /usr/bin/reflector -p https -l 10 -f 5 -c "${COUNTRY}" -x mirror.theash.xyz -x ftp.sudhip.com -x dfw.mirror.rackspace.com --sort rate --save /etc/pacman.d/mirrorlist
+        /bin/grep '^Server' /etc/pacman.d/mirrorlist | /bin/sed 's/\(.*\)/ \1/g'
       ;;
-      repos) GET_PRIVILEGE && ${SUDO_BIN} pacman -Sy;;
+      repos) GET_PRIVILEGE && /usr/bin/sudo /usr/bin/pacman -Sy;;
       system)
         GET_PRIVILEGE
-        ${SUDO_BIN} pacman -Sy --needed --noconfirm archlinux-keyring
-        pacman -Qi chaotic-keyring > /dev/null 2>&1 && ${SUDO_BIN} pacman -S --needed --noconfirm chaotic-keyring
-        ${SUDO_BIN} pacman -Su;;
+        /usr/bin/sudo /usr/bin/pacman -Sy --needed --noconfirm archlinux-keyring
+        /usr/bin/pacman -Qi chaotic-keyring > /dev/null 2>&1 && /usr/bin/sudo /usr/bin/pacman -S --needed --noconfirm chaotic-keyring
+        /usr/bin/sudo /usr/bin/pacman -Su;;
     esac
   ;;
 esac
