Added sanity checks to startvbvm

diff --git a/startvbvm b/startvbvm
--- a/startvbvm
+++ b/startvbvm
@@ -1,13 +1,20 @@
+# Copyright (c) 2013 Paul A. Hinchberger III
+#
 # A program to use VMs in VirtualBox as presets and dynamically load
 # storage devices into them.  Useful when you use VirtualBox across
 # machines of varying capabilities. 
 
-# Usage: startvbvm [preset] [vm-name]
-#
-#   preset    Any kind of label you want to use.  Script will look for
-#             ~/.startvbvm/[preset] for a list of virtual disks to attach 
-#
-#   vm-name   Name of VM to search for.  Can be partial but must be unique.
+function usage() {
+  cat <<EndOfUsageText
+Usage: startvbvm [disk-set] [vm-name]
+
+  disk-set  Filemame that lists the disk set you want to use.
+            Script will look for ~/.startvbvm/[preset]
+
+  vm-name   Name of VM to search for and use.
+            Can be partial but must be unique.
+EndOfUsageText
+}
 
 function get_vbvmid () {
   VBoxManage list vms | grep $1 | cut -d{ -f2 | cut -b1-36
@@ -21,7 +28,35 @@ function detach () {
   VBoxManage storageattach $1 --storagectl $2 --port $3 --medium none
 }
 
+# Check to see if we got two parameters sent to us.
+
+[[ -z $1 ]] && echo "Disk set unspecified" && usage && exit 1
+[[ -z $2 ]] && echo "VM name unspecified" && usage && exit 1
+
+# Check to see if the file $1 refers to exists.
+
+[[ ! -f ~/.startvbvm/$1 ]] && echo "Cannot find ~/.startvbvm/$1" && usage && exit 2
+
 VBVMID=$(get_vbvmid $2) && count=-1
+
+# Check to see if the VM exists
+
+[[ -z $VBVMID ]] && echo "Cannot find the VM whose name contains $2" && exit 3
+
+# Check to make sure we only have 1 VM UUID
+
+if [[ `echo $VBVMID | wc -m` -gt 37 ]]; then
+  echo "More than one VM name contains $2"
+  VBoxManage list vms | grep $2 | cut -d\"  -f2
+  exit 4
+fi
+
+# Make sure the vboxdrv module is loaded
+
+while [ "`lsmod | grep vboxdrv`" == "" ]; do
+  echo "Module vboxdrv not loaded."
+  sudo modprobe vboxdrv
+done
 
 while IFS= read -r vdfile; do
   count=$(($count + 1))
@@ -29,6 +64,7 @@ while IFS= read -r vdfile; do
   echo "SATA port $count $vdfile"
 done < ~/.startvbvm/$1
 
+count=-1 
 VBoxManage startvm $VBVMID
 
 echo "Waiting for process VirtualBox to terminate (5 sec check)..."
